const actorInfo={
'User':['Local intent','Chooses a local profile operation through the device UI. The LPA manages the local procedure; the eUICC enforces applicable conditions.','SGP.22 §3.2'],
'LPA':['Local Profile Assistant','Combines local profile download, discovery and management functions. This view uses LPAd, located in the device. LPAe is the eUICC-resident variant.','SGP.22 §§2.2, 3.1–3.2'],
'SM-DP+':['Profile preparation server','Prepares and binds a Profile Package to the target eUICC and participates in RSP authentication. It is not the entity that performs the final profile-state change on the card.','SGP.22 §§3.0.1, 3.1.3'],
'SM-DS':['Discovery server','Stores Event Records that let a client discover an RSP server and its pending event. It does not store the downloadable Profile Package.','SGP.22 §3.6; SGP.32 §3.9'],
'eUICC':['Secure execution boundary','Authenticates protected inputs, installs profiles and enforces profile-management rules. ISD-R handles management; each ISD-P is associated with a Profile. A Profile and an ISD-P are related, not interchangeable terms.','SGP.22 / SGP.32 §2.4'],
'eIM':['eSIM IoT remote Manager','Triggers IoT provisioning and prepares signed eUICC Packages for remote state management. In indirect download it also communicates with the SM-DP+ on behalf of the IPA.','SGP.32 §§2.9.1, 3.2.3.2'],
'IPA':['IoT Profile Assistant','Transfers packages and coordinates IoT download procedures. This view uses IPAd, located in the device; IPAe resides in the eUICC. The eUICC, not the transport function, verifies and executes signed state-management packages.','SGP.32 §§2.4.1, 2.9.1'],
'Operator':['Subscription provider','Arranges the profile order with the SM-DP+. Operator provisioning and device download are distinct parts of the overall service.','SGP.22 §2.3; SGP.32 §2.3']
};
const st=(from,to,title,iface,text,note,ref)=>({from,to,title,iface,text,note,ref});
const common22=[
st('LPA','SM-DP+','Start authentication','ES9+','The LPA contacts the selected SM-DP+, passing eUICC challenge and capability information. Activation Code, discovery or default address may supply the server context.','HTTPS transport security is distinct from eUICC–server authentication.','§§3.1.1, 3.0.1'),
st('SM-DP+','eUICC','Mutually authenticate','ES9+ / ES10b','The LPA relays authentication data. The eUICC authenticates the server; the server verifies the eUICC response and its certificate chain.','The arrow groups exchanges relayed by the LPA; it is not a direct network socket into the eUICC.','§3.0.1'),
st('LPA','SM-DP+','Request bound package','ES9+.GetBoundProfilePackage','After preparation at the eUICC, the LPA requests the Bound Profile Package from the SM-DP+.','A BPP is bound to the target eUICC. Transporting the package does not give the LPA the role of decrypting the profile.','§3.1.3'),
st('LPA','eUICC','Load and install','ES10b.LoadBoundProfilePackage','The LPA transfers the BPP. The eUICC processes the protected package and installs the profile in its secure environment.','ES8+ is the logical SM-DP+–eUICC protection relationship carried through these transports.','§3.1.3'),
st('eUICC','SM-DP+','Report installation result','ES10b / ES9+','The eUICC generates the installation result; the LPA forwards it to the SM-DP+.','Successful installation is not proof that the profile is enabled or registered on the cellular network.','§§3.1.3, 3.5')];
const data={
'22':{version:'v3.1',context:'Consumer RSP · LPAd coordinates download and local management. The eUICC is the secure installation and execution boundary.',diff:[['LPA is not IPA','SGP.22 uses LPA functions for local discovery, download and management. SGP.32 introduces the IPA and remote eIM role.'],['v3.1 also has remote management','Do not reduce SGP.22 to “local only”: §3.7 defines RPM through SM-DP+ and LPA. It is different from SGP.32 eIM Packages.'],['State is not connectivity','Installed, enabled and registered are different milestones. Multiple Enabled Profiles also make “only one enabled profile” an unsafe global rule.']],flows:[
{id:'download',name:'Download & install',kind:'REMOTE PROVISIONING',intro:'A condensed download through LPAd. Authentication and result arrows group relayed exchanges.',actors:['SM-DP+','LPA','eUICC'],steps:common22},
{id:'enable',name:'Enable profile',kind:'LOCAL PROFILE MANAGEMENT',intro:'A local enable request. Device refresh and port behavior depend on the selected SEP/MEP procedure.',actors:['User','LPA','eUICC'],steps:[st('User','LPA','Choose target profile','Local UI','The user selects the profile to enable. The LPA obtains the relevant profile information and handles the applicable user interaction.','This is local intent, not an eIM-issued PSMO.','§3.2.1'),st('LPA','eUICC','Request enable','ES10c.EnableProfile','The LPA submits EnableProfile with the applicable parameters. The eUICC checks the request and profile-policy conditions.','Consider target port and existing enabled profiles for MEP.','§§3.2.1, 5.7.16'),st('eUICC','eUICC','Apply state change','ISD-R / Profile / port','The eUICC performs the enable procedure, with refresh behavior and effects on other profiles as specified for the configuration.','An enabled profile can still fail network registration; inspect NAS separately.','§3.2.1'),st('eUICC','LPA','Return and notify','ES10c / notifications','The operation result is returned and configured notifications are handled through the LPA.','Check the resulting profile state as well as the command response.','§§3.2.1, 3.5')]},
...['Disable','Delete'].map((op,i)=>({id:op.toLowerCase(),name:op+' profile',kind:'LOCAL PROFILE MANAGEMENT',intro:op==='Delete'?'Removal of a profile is separate from disabling it.':'Disabling retains the installed profile for possible later use.',actors:['User','LPA','eUICC'],steps:[st('User','LPA','Choose '+op.toLowerCase(),'Local UI','The local user selects the target profile and the LPA handles the specified interaction.','Check the target ICCID, current state and policy conditions.',`§3.2.${i+2}`),st('LPA','eUICC',op+' request','ES10c.'+op+'Profile','The LPA invokes the corresponding eUICC function. The eUICC evaluates the operation against its current state and policy.','Do not assume an enabled profile can be directly deleted.',`§3.2.${i+2}`),st('eUICC','LPA','Result and notifications','ES10c / notifications',op==='Delete'?'On successful deletion the profile is removed; re-use requires provisioning again.':'On successful disabling the profile remains installed but is no longer enabled.','A request being sent is not evidence that the state changed.',`§§3.2.${i+2}, 3.5`)]})),
{id:'discovery',name:'SM-DS discovery',kind:'EVENT DISCOVERY',intro:'Discovery identifies a pending event and its RSP server. The profile is downloaded from SM-DP+.',actors:['SM-DP+','SM-DS','LPA'],steps:[st('SM-DP+','SM-DS','Register event','ES12','SM-DP+ registers the event with SM-DS for the relevant eUICC. SM-DS maintains the corresponding Event Record.','Event Registration is the registration operation; the Event Record is the stored discovery information.','§3.6.1'),st('LPA','SM-DS','Retrieve events','ES11','The LPA performs the authenticated event retrieval procedure for the eUICC.','Discovery does not itself install a profile.','§3.6.2'),st('SM-DS','LPA','Return Event Records','ES11','The returned records provide the event identifier and RSP-server context needed to continue.','The EventID is not the downloadable BPP.','§3.6.2'),st('LPA','SM-DP+','Continue at RSP server','ES9+','The LPA uses the discovery information to contact the relevant SM-DP+ and continue the applicable procedure.','Event deletion is a separate procedure; see §3.6.3.','§§3.1.1, 3.6')]},
{id:'rpm',name:'Remote management (RPM)',kind:'SGP.22 v3.1 REMOTE MANAGEMENT',intro:'SGP.22 has its own RPM procedure. Do not map it onto the eIM/IPA architecture.',actors:['SM-DP+','LPA','eUICC'],steps:[st('LPA','SM-DP+','Initiate RPM','ES9+','The LPA initiates the RPM procedure with the SM-DP+ using the relevant event/server context.','The SGP.22 server role remains SM-DP+; this is not ESipa.','§3.7.1'),st('SM-DP+','LPA','Download RPM package','RPM Package','An RPM Package is downloaded through the LPA. Applicable checks and user interaction are handled in the procedure.','Do not assume all remotely requested changes bypass user consent.','§3.7.2'),st('LPA','eUICC','Execute RPM commands','RPM execution','The LPA transfers the RPM Package; the eUICC executes the contained commands sequentially according to the procedure.','RPM Package and SGP.32 signed eUICC Package are different mechanisms.','§3.7.3')]}]},
'32':{version:'v1.3',context:'IoT RSP · eIM orchestrates remote management, IPA carries the exchanges, and the eUICC verifies and executes. Diagrams use IPAd.',diff:[['ESipa and ESep are different','ESipa connects eIM and IPA. ESep is the logical end-to-end eIM–eUICC interface for protected eUICC Packages.'],['PSMO is not ES10c','An eIM prepares signed eUICC Packages containing Profile State Management Operations. ES10c support is outside SGP.32’s scope (§2.3).'],['Direct vs indirect download','Direct: IPA contacts SM-DP+ via ES9+. Indirect: eIM contacts SM-DP+ via ES9+′ and relays through ESipa. ES8+ still protects the profile end to end.']],flows:[]}
};
for(const indirect of [false,true]) data['32'].flows.push({id:indirect?'indirect':'download',name:indirect?'Indirect download':'Direct download',kind:'PROFILE DOWNLOAD',intro:indirect?'The eIM mediates RSP-server communication. The profile remains protected for the target eUICC.':'The IPA communicates directly with SM-DP+. An eIM trigger is the illustrated initiation option.',actors:indirect?['SM-DP+','eIM','IPA','eUICC']:['eIM','SM-DP+','IPA','eUICC'],steps:[
st('eIM','IPA','Trigger download','ESipa','The IPA receives a ProfileDownloadTriggerRequest in an eIM Package. Other specified initiation options also exist.','Retrieval and injection are distinct eIM Package delivery options (§3.1.1).',`§3.2.3.${indirect?2:1}`),
st(indirect?'eIM':'IPA','SM-DP+','Authenticate via server',indirect?'ES9+′ / ESipa':'ES9+ / ES10b','RSP authentication exchanges are carried between the SM-DP+ and eUICC, using '+(indirect?'eIM and IPA as intermediaries.':'the IPA as intermediary.'),'The eUICC verifies the RSP server; TLS alone is not the full RSP authentication procedure.',`§§3.2.2, 3.2.3.${indirect?2:1}`),
st('SM-DP+',indirect?'eIM':'IPA','Deliver bound package',indirect?'ES9+′ → ESipa':'ES9+','The bound package is delivered '+(indirect?'to the eIM and relayed to the IPA.':'to the IPA.'),'ES8+ protection is end to end between SM-DP+ and eUICC, not terminated by the eIM.',`§3.2.3.${indirect?2:1}`),
st('IPA','eUICC','Load and install','ES10b.LoadBoundProfilePackage','IPAd transfers the package to the eUICC for secure processing and installation.','IPAe is the alternative eUICC-resident placement; this external IPAd boundary does not apply unchanged.',`§3.2.3.${indirect?2:1}`),
st('eUICC','SM-DP+','Relay installation result',indirect?'ES10b / ESipa / ES9+′':'ES10b / ES9+','The installation result is relayed back through the download path.','Immediate enabling is a separately configured feature with conditions; download success does not universally imply enablement (§2.9.2).',`§3.2.3.${indirect?2:1}`)]});
for(const [i,op] of ['Enable','Disable','Delete'].entries()) data['32'].flows.push({id:op.toLowerCase(),name:op+' profile',kind:'REMOTE PROFILE STATE MANAGEMENT',intro:'eIM requests and signs; IPA transports; eUICC verifies and changes the profile state.',actors:['eIM','IPA','eUICC'],steps:[
st('eIM','eIM','Prepare signed request','ESep · signed eUICC Package',`The eIM constructs a signed eUICC Package containing the ${op.toLowerCase()} PSMO for the target profile.`,'The outer eIM Package is not synonymous with the signed eUICC Package it carries.',`§§2.9.1, 3.4.${i+1}`),
st('eIM','IPA','Transfer package','ESipa','The eIM Package containing the signed eUICC Package is transferred to IPA.','Transport security does not replace the eUICC’s verification of the signed package.','§3.1.1'),
st('IPA','eUICC','Load eUICC package','ES10b.LoadEuiccPackage','IPAd passes the signed eUICC Package to the eUICC.','IPA transports the command; it does not assume the eIM’s signing authority.','§3.3.1'),
st('eUICC','eUICC','Verify and execute','Signature / EID / replay counter',`The eUICC verifies the eIM signature, EID and replay counter, then processes the ${op.toLowerCase()} operation under its state and policy rules.`,'State transitions follow the specified REFRESH/reset handling. A rejected package must not be treated as a completed change.',`§§3.3.1, 3.4.${i+1}`),
st('eUICC','eIM','Return signed result','ES10b → ESipa · ESep','IPA forwards the signed eUICC Package Result. The eIM verifies its signature before processing the execution result.','Read the operation result and resulting state; a transport acknowledgement alone is insufficient.','§2.9.1')]});
data['32'].flows.push({id:'discovery',name:'SM-DS discovery',kind:'EVENT DISCOVERY',intro:'Shown: event retrieval by eIM. The standard also defines direct retrieval by IPA.',actors:['SM-DP+','SM-DS','eIM','IPA'],steps:[st('SM-DP+','SM-DS','Register event','ES12','SM-DP+ registers the event at SM-DS for the relevant eUICC.','SM-DS holds discovery information, not profile content.','§3.9.1'),st('eIM','SM-DS','Retrieve events via eIM','ES11′','The eIM performs the event retrieval procedure using the required eUICC authentication data.','The grouped exchange involves IPA/eUICC support; it is not an unauthenticated server lookup.','§3.9.2.2'),st('eIM','IPA','Trigger next procedure','ESipa','The event context can be used to trigger the applicable profile download.','Alternatively, IPA retrieves events directly over ES11 (§3.9.2.1).','§§3.9.2, 3.2.1')]});
let spec='22',flowId='download',stepIndex=0;
const $=id=>document.getElementById(id);
function flow(){return data[spec].flows.find(f=>f.id===flowId)}
function render(){const d=data[spec],f=flow();document.querySelectorAll('[data-spec]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.spec===spec)));$('context').textContent=d.context;$('flows').innerHTML=d.flows.map(x=>`<button data-flow="${x.id}" class="${x.id===flowId?'active':''}" aria-current="${x.id===flowId?'true':'false'}">${x.name}</button>`).join('');$('flow-kind').textContent=f.kind;$('flow-title').textContent=f.name;$('flow-intro').textContent=f.intro;$('count').textContent=f.steps.length+' steps';$('diagram').style.setProperty('--actors',f.actors.length);$('diagram').innerHTML=`<div class="security">${spec==='32'&&['enable','disable','delete'].includes(flowId)?'ESep · eIM ↔ eUICC':flowId==='download'||flowId==='indirect'?'ES8+ · SM-DP+ ↔ eUICC':'Logical actors · grouped exchanges'}</div><div class="actors">${f.actors.map(a=>`<button class="actor" data-actor="${a}">${a}</button>`).join('')}</div>`+f.steps.map((s,i)=>{const a=f.actors.indexOf(s.from),b=f.actors.indexOf(s.to),n=f.actors.length,left=(Math.min(a,b)+.5)/n*100,width=Math.abs(a-b)/n*100;return `<button class="step ${i===stepIndex?'selected':''}" data-step="${i}" aria-label="Step ${i+1}: ${s.title}, ${s.from} to ${s.to}" aria-pressed="${i===stepIndex}" style="--left:${left}%;--width:${width}%;--label:${Math.min(left,50)}%"><span class="step-label"><span class="step-no">${String(i+1).padStart(2,'0')}</span>${s.title}</span><span class="arrow ${a>b?'reverse':''} ${a===b?'self':''}"></span></button>`}).join('');$('differences').innerHTML=d.diff.map(([t,p])=>`<article><h3>${t}</h3><p>${p}</p></article>`).join('');showStep();}
function showStep(){const f=flow(),s=f.steps[stepIndex];document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('selected',+b.dataset.step===stepIndex);b.setAttribute('aria-pressed',String(+b.dataset.step===stepIndex))});document.querySelectorAll('[data-actor]').forEach(b=>b.classList.remove('selected'));$('detail').innerHTML=`<p class="eyebrow">STEP ${String(stepIndex+1).padStart(2,'0')} / ${f.steps.length}</p><h2>${s.title}</h2><span class="tag">${s.iface}</span><p>${s.text}</p><p class="note">${s.note}</p><div class="source">${s.from} → ${s.to}<br>SGP.${spec} ${data[spec].version} · ${s.ref}<br>Summary of the cited procedure</div>`;$('progress').textContent=`Step ${stepIndex+1} of ${f.steps.length}`;$('previous').disabled=stepIndex===0;$('next').disabled=stepIndex===f.steps.length-1;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.spec){spec=b.dataset.spec;flowId=data[spec].flows.some(f=>f.id===flowId)?flowId:'download';stepIndex=0;render()}else if(b.dataset.flow){flowId=b.dataset.flow;stepIndex=0;render()}else if(b.dataset.step!==undefined){stepIndex=+b.dataset.step;showStep()}else if(b.dataset.actor){const a=b.dataset.actor,[title,text,ref]=actorInfo[a];document.querySelectorAll('[data-actor]').forEach(x=>x.classList.toggle('selected',x===b));$('detail').innerHTML=`<p class="eyebrow">ACTOR / ENTITY</p><h2>${a}</h2><span class="tag">${title}</span><p>${text}</p><div class="source">${ref}<br>Select a flow step to resume the procedure.</div>`}else if(b.id==='previous'&&stepIndex>0){stepIndex--;showStep()}else if(b.id==='next'&&stepIndex<flow().steps.length-1){stepIndex++;showStep()}});
render();
